modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"

[[mods]]

modId="spicyminer"
version="${file.jarVersion}"
displayName="Spicy VeinMiner"
credits="Dank memes"
authors="Zach Kozar"
description='''
	Veinminer, but spicy
'''

[[dependencies.spicyminer]]
    modId="spicycore"
    mandatory=true
    versionRange="[1.16.5-2.0,)"
    ordering="BEFORE"
    side="BOTH"
