package net.masterzach32.spicyminer.config

import com.spicymemes.core.util.ifModLoaded
import net.masterzach32.spicyminer.api.IMCHelper
import net.minecraft.util.ResourceLocation

object Tools {

    fun addAllTools() {
        addToolSet(ToolType("hammer"), HAMMER_ARRAY)
        addToolSet(ToolType("drill"), DRILL_ARRAY)
        addToolSet(ToolType("pickaxe"), PICKAXE_ARRAY)
        addToolSet(ToolType("shovel"), SHOVEL_ARRAY)
        addToolSet(ToolType("axe"), AXE_ARRAY)
        addToolSet(ToolType("multitool"), MULTITOOL_ARRAY)
    }

    private fun addToolSet(toolType: ToolType, tools: List<ResourceLocation>) {
        tools.forEach { tool ->
            ifModLoaded(tool.resourceDomain) {
                IMCHelper.addTool(toolType.name, tool)
            }
        }
    }

    // list of non-vanilla tools. Any tools here will be automatically added if their mod is loaded.

    val HAMMER_ARRAY = listOf(
            "redstonearsenal:tool.hammer_flux",
            "thermalfoundation:tool.hammer_aluminum",
            "thermalfoundation:tool.hammer_bronze",
            "thermalfoundation:tool.hammer_constantan",
            "thermalfoundation:tool.hammer_copper",
            "thermalfoundation:tool.hammer_diamond",
            "thermalfoundation:tool.hammer_electrum",
            "thermalfoundation:tool.hammer_gold",
            "thermalfoundation:tool.hammer_invar",
            "thermalfoundation:tool.hammer_iron",
            "thermalfoundation:tool.hammer_lead",
            "thermalfoundation:tool.hammer_nickel",
            "thermalfoundation:tool.hammer_platinum",
            "thermalfoundation:tool.hammer_silver",
            "thermalfoundation:tool.hammer_steel",
            "thermalfoundation:tool.hammer_stone",
            "thermalfoundation:tool.hammer_tin",
            "thermalfoundation:tool.hammer_wood",
            "embers:auto_hammer",
            "embers:grandhammer",
            "embers:tinker_hammer",
            "roots:diamond_hammer",
            "roots:gold_hammer",
            "roots:iron_hammer",
            "roots:stone_hammer",
            "roots:wood_hammer",
            "techreborn:diamondjackhammer",
            "techreborn:ironjackhammer",
            "techreborn:steeljackhammer"
    ).map { ResourceLocation(it) }

    val DRILL_ARRAY = listOf(
            "actuallyadditions:item_drill",
            "immersiveengineering:drill",
            "techreborn:advanceddrill",
            "techreborn:diamonddrill",
            "techreborn:irondrill"
    ).map { ResourceLocation(it) }

    val PICKAXE_ARRAY = listOf(
            "appliedenergistics2:item.ToolCertusQuartzPickaxe",
            "appliedenergistics2:item.ToolNetherQuartzPickaxe",
            "BiomesOPlenty:pickaxeAmethyst",
            "BiomesOPlenty:pickaxeMud",
            "IC2:itemToolBronzePickaxe",
            "IC2:itemToolDDrill",
            "IC2:itemToolDrill",
            "IC2:itemToolIridiumDrill",
            "tconstruct:pickaxe",
            "redstonearsenal:tool.pickaxe_flux",
            "thermalfoundation:tool.pickaxe_aluminum",
            "thermalfoundation:tool.pickaxe_bronze",
            "thermalfoundation:tool.pickaxe_constantan",
            "thermalfoundation:tool.pickaxe_copper",
            "thermalfoundation:tool.pickaxe_electrum",
            "thermalfoundation:tool.pickaxe_invar",
            "thermalfoundation:tool.pickaxe_lead",
            "thermalfoundation:tool.pickaxe_nickel",
            "thermalfoundation:tool.pickaxe_platinum",
            "thermalfoundation:tool.pickaxe_silver",
            "thermalfoundation:tool.pickaxe_steel",
            "thermalfoundation:tool.pickaxe_tin",
            "actuallyadditions:item_pickaxe_crystal_black",
            "actuallyadditions:item_pickaxe_crystal_blue",
            "actuallyadditions:item_pickaxe_crystal_green",
            "actuallyadditions:item_pickaxe_crystal_light_blue",
            "actuallyadditions:item_pickaxe_crystal_red",
            "actuallyadditions:item_pickaxe_crystal_white",
            "actuallyadditions:item_pickaxe_emerald",
            "actuallyadditions:item_pickaxe_obsidian",
            "actuallyadditions:item_pickaxe_quartz",
            "appliedenergistics2:certus_quartz_pickaxe",
            "appliedenergistics2:nether_quartz_pickaxe",
            "astralsorcery:itemchargedcrystalpickaxe",
            "astralsorcery:itemcrystalpickaxe",
            "cavern:aquamarine_pickaxe",
            "cavern:composite_pickaxe",
            "cavern:hexcite_pickaxe",
            "cavern:ice_pickaxe",
            "cavern:magnite_pickaxe",
            "cyclicmagic:emerald_pickaxe",
            "cyclicmagic:sandstone_pickaxe",
            "draconicevolution:draconic_pick",
            "draconicevolution:wyvern_pick",
            "embers:pickaxe_aluminum",
            "embers:pickaxe_bronze",
            "embers:pickaxe_clockwork",
            "embers:pickaxe_copper",
            "embers:pickaxe_dawnstone",
            "embers:pickaxe_electrum",
            "embers:pickaxe_lead",
            "embers:pickaxe_nickel",
            "embers:pickaxe_silver",
            "embers:pickaxe_tin",
            "forestry:broken_bronze_pickaxe",
            "forestry:bronze_pickaxe",
            "forestry:kit_pickaxe",
            "minecraft:diamond_pickaxe",
            "minecraft:golden_pickaxe",
            "minecraft:iron_pickaxe",
            "minecraft:stone_pickaxe",
            "minecraft:wooden_pickaxe",
            "mysticalagriculture:inferium_pickaxe",
            "mysticalagriculture:intermedium_pickaxe",
            "mysticalagriculture:prudentium_pickaxe",
            "mysticalagriculture:superium_pickaxe",
            "mysticalagriculture:supremium_pickaxe",
            "nmmlib:pickaxe_bronze",
            "nmmlib:pickaxe_copper",
            "nmmlib:pickaxe_electrum",
            "nmmlib:pickaxe_invar",
            "nmmlib:pickaxe_lead",
            "nmmlib:pickaxe_nickel",
            "nmmlib:pickaxe_platinum",
            "nmmlib:pickaxe_silver",
            "nmmlib:pickaxe_tin",
            "spicypineapple:pineapple_pickaxe",
            "spicypineapple:energized_pickaxe",
            "psi:psimetal_pickaxe",
            "techreborn:bronzepickaxe",
            "techreborn:peridotpickaxe",
            "techreborn:rubypickaxe",
            "techreborn:sapphirepickaxe"
    ).map { ResourceLocation(it) }

    val SHOVEL_ARRAY = listOf(
            "appliedenergistics2:item.ToolCertusQuartzSpade",
            "appliedenergistics2:item.ToolNetherQuartzSpade",
            "BiomesOPlenty:shovelAmethyst",
            "BiomesOPlenty:shovelMud",
            "IC2:itemToolBronzeSpade",
            "IC2:itemToolBronzeSpade",
            "IC2:itemToolBronzeSpade",
            "IC2:itemToolBronzeSpade",
            "tconstruct:mattock",
            "tconstruct:shovel",
            "redstonearsenal:tool.shovel_flux",
            "thermalfoundation:tool.shovel_aluminum",
            "thermalfoundation:tool.shovel_bronze",
            "thermalfoundation:tool.shovel_constantan",
            "thermalfoundation:tool.shovel_copper",
            "thermalfoundation:tool.shovel_electrum",
            "thermalfoundation:tool.shovel_invar",
            "thermalfoundation:tool.shovel_lead",
            "thermalfoundation:tool.shovel_nickel",
            "thermalfoundation:tool.shovel_platinum",
            "thermalfoundation:tool.shovel_silver",
            "thermalfoundation:tool.shovel_steel",
            "thermalfoundation:tool.shovel_tin",
            "actuallyadditions:item_shovel_crystal_black",
            "actuallyadditions:item_shovel_crystal_blue",
            "actuallyadditions:item_shovel_crystal_green",
            "actuallyadditions:item_shovel_crystal_light_blue",
            "actuallyadditions:item_shovel_crystal_red",
            "actuallyadditions:item_shovel_crystal_white",
            "actuallyadditions:item_shovel_emerald",
            "actuallyadditions:item_shovel_obsidian",
            "actuallyadditions:item_shovel_quartz",
            "astralsorcery:itemchargedcrystalshovel",
            "astralsorcery:itemcrystalshovel",
            "cavern:aquamarine_shovel",
            "cavern:composite_shovel",
            "cavern:hexcite_shovel",
            "cavern:ice_shovel",
            "cavern:magnite_shovel",
            "draconicevolution:draconic_shovel",
            "draconicevolution:wyvern_shovel",
            "embers:shovel_aluminum",
            "embers:shovel_bronze",
            "embers:shovel_copper",
            "embers:shovel_dawnstone",
            "embers:shovel_electrum",
            "embers:shovel_lead",
            "embers:shovel_nickel",
            "embers:shovel_silver",
            "embers:shovel_tin",
            "forestry:broken_bronze_shovel",
            "forestry:bronze_shovel",
            "forestry:kit_shovel",
            "minecraft:diamond_shovel",
            "minecraft:golden_shovel",
            "minecraft:iron_shovel",
            "minecraft:stone_shovel",
            "minecraft:wooden_shovel",
            "mysticalagriculture:inferium_shovel",
            "mysticalagriculture:intermedium_shovel",
            "mysticalagriculture:prudentium_shovel",
            "mysticalagriculture:superium_shovel",
            "mysticalagriculture:supremium_shovel",
            "nmmlib:shovel_bronze",
            "nmmlib:shovel_copper",
            "nmmlib:shovel_electrum",
            "nmmlib:shovel_invar",
            "nmmlib:shovel_lead",
            "nmmlib:shovel_nickel",
            "nmmlib:shovel_platinum",
            "nmmlib:shovel_silver",
            "nmmlib:shovel_tin",
            "spicypineapple:pineapple_shovel",
            "spicypineapple:energized_shovel",
            "psi:psimetal_shovel"
    ).map { ResourceLocation(it) }

    val AXE_ARRAY = listOf(
            "appliedenergistics2:item.ToolCertusQuartzAxe",
            "appliedenergistics2:item.ToolNetherQuartzAxe",
            "BiomesOPlenty:axeAmethyst",
            "BiomesOPlenty:axeMud",
            "IC2:itemToolBronzeAxe",
            "IC2:itemToolBronzeAxe",
            "IC2:itemToolBronzeAxe",
            "IC2:itemToolBronzeAxe",
            "IC2:itemToolChainsaw",
            "IC2:itemToolChainsaw",
            "IC2:itemToolChainsaw",
            "IC2:itemToolChainsaw",
            "tconstruct:hatchet",
            "redstonearsenal:tool.axe_flux",
            "thermalfoundation:tool.axe_aluminum",
            "thermalfoundation:tool.axe_bronze",
            "thermalfoundation:tool.axe_constantan",
            "thermalfoundation:tool.axe_copper",
            "thermalfoundation:tool.axe_electrum",
            "thermalfoundation:tool.axe_invar",
            "thermalfoundation:tool.axe_lead",
            "thermalfoundation:tool.axe_nickel",
            "thermalfoundation:tool.axe_platinum",
            "thermalfoundation:tool.axe_silver",
            "thermalfoundation:tool.axe_steel",
            "thermalfoundation:tool.axe_tin",
            "actuallyadditions:item_axe_crystal_black",
            "actuallyadditions:item_axe_crystal_blue",
            "actuallyadditions:item_axe_crystal_green",
            "actuallyadditions:item_axe_crystal_light_blue",
            "actuallyadditions:item_axe_crystal_red",
            "actuallyadditions:item_axe_crystal_white",
            "actuallyadditions:item_axe_emerald",
            "actuallyadditions:item_axe_obsidian",
            "actuallyadditions:item_axe_quartz",
            "appliedenergistics2:certus_quartz_axe",
            "appliedenergistics2:nether_quartz_axe",
            "astralsorcery:itemchargedcrystalaxe",
            "astralsorcery:itemcrystalaxe",
            "cavern:aquamarine_axe",
            "cavern:composite_axe",
            "cavern:hexcite_axe",
            "cavern:ice_axe",
            "cavern:magnite_axe",
            "cavern:manalite_axe",
            "cyclicmagic:emerald_axe",
            "cyclicmagic:sandstone_axe",
            "draconicevolution:draconic_axe",
            "draconicevolution:wyvern_axe",
            "embers:axe_aluminum",
            "embers:axe_bronze",
            "embers:axe_clockwork",
            "embers:axe_copper",
            "embers:axe_dawnstone",
            "embers:axe_electrum",
            "embers:axe_lead",
            "embers:axe_nickel",
            "embers:axe_silver",
            "embers:axe_tin",
            "extrautils2:fireaxe",
            "minecraft:diamond_axe",
            "minecraft:golden_axe",
            "minecraft:iron_axe",
            "minecraft:stone_axe",
            "minecraft:wooden_axe",
            "mysticalagriculture:inferium_axe",
            "mysticalagriculture:intermedium_axe",
            "mysticalagriculture:prudentium_axe",
            "mysticalagriculture:superium_axe",
            "mysticalagriculture:supremium_axe",
            "nmmlib:axe_bronze",
            "nmmlib:axe_copper",
            "nmmlib:axe_electrum",
            "nmmlib:axe_invar",
            "nmmlib:axe_lead",
            "nmmlib:axe_nickel",
            "nmmlib:axe_platinum",
            "nmmlib:axe_silver",
            "nmmlib:axe_tin",
            "spicypineapple:pineapple_axe",
            "spicypineapple:energized_axe",
            "psi:psimetal_axe",
            "techreborn:bronzeaxe",
            "techreborn:peridotaxe",
            "techreborn:rubyaxe",
            "techreborn:sapphireaxe"
    ).map { ResourceLocation(it) }

    val MULTITOOL_ARRAY = listOf(
            "actuallyadditions:diamond_paxel",
            "actuallyadditions:emerald_paxel",
            "actuallyadditions:gold_paxel",
            "actuallyadditions:iron_paxel",
            "actuallyadditions:item_paxel_crystal_black",
            "actuallyadditions:item_paxel_crystal_blue",
            "actuallyadditions:item_paxel_crystal_green",
            "actuallyadditions:item_paxel_crystal_light_blue",
            "actuallyadditions:item_paxel_crystal_red",
            "actuallyadditions:item_paxel_crystal_white",
            "actuallyadditions:obsidian_paxel",
            "actuallyadditions:quartz_paxel",
            "actuallyadditions:stone_paxel",
            "actuallyadditions:wooden_paxel"
    ).map { ResourceLocation(it) }

}